import tables, base64

var assets = initTable[string, string]()

proc getAsset*(path: string): string = 
  result = assets[path].decode()

assets.add("public/styles/main.css",  """Ym9keXsNCiAgICBiYWNrZ3JvdW5kLWNvbG9yOiBibHVldmlvbGV0Ow0KfQ0KDQojc3BhY2VyMXsNCiAgICBkaXNwbGF5OiBibG9jazsNCiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7DQogICAgaGVpZ2h0OiAzMy4zMyU7DQp9DQoNCiN2ZXJ0X3NwYWNlcnsNCiAgICBoZWlnaHQ6IDMzLjMzJTsNCn0NCg0KbGFiZWx7DQogICAgY29sb3I6IGJsYWNrOw0KfQ0KDQojc3BhY2Vyew0KICAgIHBhZGRpbmctbGVmdDogMjAlOw0KICAgIHBhZGRpbmctcmlnaHQ6IDIwJTsNCiAgICBwYWRkaW5nLXRvcDogMiU7DQogICAgcGFkZGluZy1ib3R0b206IDIlOw0KfQ0KDQojbWFpbl9mb3Jtew0KICAgIHBhZGRpbmc6IDUlOw0KICAgIGJhY2tncm91bmQtY29sb3I6IGFudGlxdWV3aGl0ZTsNCn0=""" )

assets.add("public/styles/success.css",  """Ym9keXsNCiAgICBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoNzIsIDE0MSwgMyk7DQp9DQoNCmgxew0KICAgIGNvbG9yOiBibGFjazsNCn0NCg0KI3NwYWNlcnsNCiAgICBkaXNwbGF5OiBibG9jazsNCiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7DQp9""" )

